# Generated by Django 3.0.7 on 2020-07-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
