# Generated by Django 3.0.7 on 2020-07-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20200731_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('python', 'Python'), ('sql', 'SQL'), ('javascript', 'JavaScript'), ('java', 'Java')], default=None, max_length=100),
        ),
    ]
