# Generated by Django 3.0.7 on 2020-08-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20200801_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceresults',
            name='practiceTestNumber',
            field=models.IntegerField(default=1),
        ),
    ]
