# Generated by Django 3.0.7 on 2020-08-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20200801_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceresults',
            name='practiceTestNumber',
        ),
    ]
