# Generated by Django 3.0.7 on 2020-08-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_practiceresults_practicetestnumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PracticeResults',
            new_name='PracticeResult',
        ),
    ]
