# Generated by Django 3.0.7 on 2020-08-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20200801_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceresult',
            name='practiceTestNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
